observable_pointcloud_map_creator_node:
  ros__parameters:
    input_pcd_path: "/home/kazuma/map_ws/input/ex_5th_raw_subsampled.pcd"
    output_dir: "output"
    grid_size: 30.0
    voxel_leaf_size_: 0.5
    hpr_radius: -1.0
